name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Deploy to production
        run: echo "Deploying to production..."
      - name: sending message on slack
        if: success()
        run: |
              curl -X POST -H 'Content-type: application/json' \
              --data '{"text":"✅ GitHub Action Succeeded for *MyApp*"}' \
              ${{ env.SLACK_WEBHOOK_URL }}