name: Deploy to Production

on:
  workflow_dispatch:

jobs:

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Deploy to production
        run: echo "Deploying to production..."
