name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Deploy to production
        run: echo "Deploying to production..."
      - name: sending message on slack
        if: success()
        run: |
             curl -X POST --data-urlencode "payload={\"channel\": \"#new-channel\", \"username\": \"webhookbot\", \"text\": \"This is posted to #new-channel and comes from a bot named webhookbot.\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/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
